FROM debian:stretch
# install basic tools and PHP dependencies

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libxml2 \
        libxml2-dev \
        libpq-dev \
        libmcrypt-dev \
        libonig-dev \
        libssl-dev \
        mysql-client \
        git \
        unixodbc-dev \
        procps \
        mc \
        wget \
        telnet \
        netcat \
        net-tools \
        screen \
        inetutils-ping \
        dnsutils \
        iproute2 \
        screen \
        tmux \
        build-essential \
        bison \
        re2c \
        libssl-dev \
        libcurl4-openssl-dev \
        pkg-config \
        libbz2-dev \
        libxpm-dev \
        libxpm4 \
        lemon \
        libtidy-dev \
        apt-utils \
        libxslt1.1 \
        libxslt1-dev \
	libpcre3-dev \
	libexpat1-dev \
	sqlite
